const students = [
    { "id": 1001, "name": "Alice Johnson", "course": "Computer Science" },
    { "id": 1002, "name": "Brian Smith", "course": "Information Technology" },
    { "id": 1003, "name": "Catherine Lee", "course": "Business Administration" },
    { "id": 1004, "name": "Daniel Brown", "course": "Mechanical Engineering" },
    { "id": 1005, "name": "Emma Wilson", "course": "Electrical Engineering" },
    { "id": 1006, "name": "Frank Miller", "course": "Civil Engineering" },
    { "id": 1007, "name": "Grace Taylor", "course": "Mathematics" },
    { "id": 1008, "name": "Henry Anderson", "course": "Physics" },
    { "id": 1009, "name": "Isabella Thomas", "course": "Chemistry" },
    { "id": 1010, "name": "Jack Moore", "course": "Biology" },
    { "id": 1011, "name": "Karen Martin", "course": "Economics" },
    { "id": 1012, "name": "Liam Garcia", "course": "Data Science" },
    { "id": 1013, "name": "Mia Rodriguez", "course": "Artificial Intelligence" },
    { "id": 1014, "name": "Noah Martinez", "course": "Software Engineering" },
    { "id": 1015, "name": "Olivia Hernandez", "course": "Cyber Security" },
    { "id": 1016, "name": "Peter Lopez", "course": "Accounting" },
    { "id": 1017, "name": "Quinn Gonzalez", "course": "Finance" },
    { "id": 1018, "name": "Ryan Perez", "course": "Marketing" },
    { "id": 1019, "name": "Sophia Clark", "course": "Psychology" },
    { "id": 1020, "name": "Thomas Lewis", "course": "Environmental Science" },  
    { "id": 1021, "name": "Uma Patel", "course": "Human Resource Management" },
    { "id": 1022, "name": "Victor Nguyen", "course": "Cloud Computing" },
    { "id": 1023, "name": "Wendy Kim", "course": "Digital Media" },
    { "id": 1024, "name": "Xavier Collins", "course": "Game Development" },
    { "id": 1025, "name": "Yar Ahmed", "course": "Health Informatics" },
    { "id": 1026, "name": "Zachary Scott", "course": "Operations Management" },
    { "id": 1027, "name": "Amelia Turner", "course": "Biomedical Engineering" },
    { "id": 1028, "name": "Benjamin Hall", "course": "Statistics" },
    { "id": 1029, "name": "Chloe Young", "course": "Sociology" },
    { "id": 1030, "name": "David King", "course": "Supply Chain Management" },
    { "id": 1031, "name": "Ella Wright", "course": "UI/UX Design" },
    { "id": 1032, "name": "Felix Adams", "course": "Robotics" },
    { "id": 1033, "name": "Hannah Baker", "course": "International Relations" },
    { "id": 1034, "name": "Ian Nelson", "course": "Network Engineering" },
    { "id": 1035, "name": "Julia Carter", "course": "Entrepreneurship" },
    { "id": 1036, "name": "Kevin Mitchell", "course": "DevOps Engineering" },
    { "id": 1037, "name": "Laura Perez", "course": "Public Health" },
    { "id": 1038, "name": "Michael Roberts", "course": "Blockchain Technology" },
    { "id": 1039, "name": "Natalie Evans", "course": "Forensic Science" },
    { "id": 1040, "name": "Oscar Rivera", "course": "Machine Learning" }
]


export default students;